# This is a basic workflow to help you get started with Actions

name: dev CI

# Controls when the action will run. 
on:
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        run: |
          chmod +x compile.sh
          ./compile.sh

      - name:  package
        run: |
          brew install create-dmg
          create-dmg \
          --volname "ShadowsocksX-NG" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --hide-extension "ShadowsocksX-NG.app" \
          --app-drop-link 600 185 \
          "ShadowsocksX-NG.dmg" \
          "build/root/Applications/"
      
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ShadowsocksX-NG
          path: ShadowsocksX-NG.dmg
          retention-days: 5

