name: main CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: macos-10.15

    steps:

      - uses: actions/checkout@v2

      - name: build
        run: |
          chmod +x compile.sh
          ./compile.sh

      - name:  package
        run: |
          npm install -g appdmg
          mkdir -p build/releases
          appdmg spec.json build/releases/ShadowsocksX-NG-${GITHUB_REF#refs/tags/}.dmg
      
      - name: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          files: build/releases/*
          prerelease: ${{ contains(github.ref, '-') }}